---
# tasks file for webserver
- name: Yum -- Update the instance
  yum:
    name: "*"
    state: latest
    update_only: yes

- name: Yum -- Install git, wget, go, 
  yum:
    name:
      - git
      - wget
      - go

- name: Command -- Install Nginx
  command: /usr/bin/amazon-linux-extras install nginx1 -y

- name: Template -- Overwrite the Server 1 index.html file
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  notify:
    - Restart Nginx Service

- name: Command -- Installing Necessary Go Libraries
  command:
    cmd: /usr/bin/go get -u -v github.com/confluentinc/confluent-kafka-go/kafka
    chdir: /home/ec2-user

- name: Command -- Installing Necessary Go Libraries
  command:
    cmd: /usr/bin/go get -u -v github.com/gorilla/mux
    chdir: /home/ec2-user

- name: Template -- Overwrite the Server 1 consumer.go file
  template:
    src: consumer.go.j2
    dest: /home/ec2-user/consumer.go
  notify:
    - Build Consumer Go Binary
    - Restart Consumer Service

- name: Copy -- the consumer servie file
  copy:
    src: consumer.service
    dest: /etc/systemd/system/consumer.service
  notify:
    - Reload Daemons
    - Restart Consumer Service
