---
# tasks file for webserver
- name: Update the instance
  yum:
    name: "*"
    state: latest
    update_only: yes

- name: Install git, wget, go, 
  yum:
    name:
      - git
      - wget
      - go

- name: Install Nginx
  command: /usr/bin/amazon-linux-extras install nginx1 -y

- name: Overwrite the Server 1 index.html file
  copy:
    src: index_1.html
    dest: /usr/share/nginx/html/index.html
  when: webserver_num == 1

- name: Overwrite the Server 2 index.html file
  copy:
    src: index_2.html
    dest: /usr/share/nginx/html/index.html
  when: webserver_num == 2

- name: Overwrite the Server 3 index.html file
  copy:
    src: index_3.html
    dest: /usr/share/nginx/html/index.html
  when: webserver_num == 3

- name: Start Nginx Server
  service:
    name: nginx
    enabled: yes
    state: started

- name: Overwrite the Server 1 consumer.go file
  copy:
    src: consumer_1.go
    dest: /home/ec2-user/consumer.go
  when: webserver_num == 1

- name: Overwrite the Server 2 consumer.go file
  copy:
    src: consumer_2.go
    dest: /home/ec2-user/consumer.go
  when: webserver_num == 2

- name: Overwrite the Server 3 consumer.go file
  copy:
    src: consumer_3.go
    dest: /home/ec2-user/consumer.go
  when: webserver_num == 3

- name: Build the Consumer GO Binary
  command:
    cmd: /usr/bin/go build consumer.go
    chdir: /home/ec2-user/

- name: Copy the consumer servie file
  copy:
    src: consumer.service
    dest: /etc/systemd/system/consumer.service

- name: Start Consumer service
  service:
    name: consumer
    enabled: yes
    state: started

- name: Reload Service Daemons in case of update
  command: /usr/bin/systemctl daemon-reload
