Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 22, host: 2222, auto_correct:true
  config.vm.define "cust" do |cust|
    cust.vm.box = "bento/centos-8"
    cust.vm.hostname = "VM-My-Vagrant"
    cust.vm.network "private_network", ip: "192.168.69.69"
    cust.ssh.insert_key = true
    cust.vm.provision "file", source: "~/.ssh/id_rsa_vagrant.pub", destination: "~/.ssh/authorized_keys"
  end
end
