---
# tasks file for zookeeper
- name: Update the instance
  yum:
    name: "*"
    state: latest
    update_only: yes

- name: Install git, wget, go, 
  yum:
    name:
      - git
      - wget
      - go

- name: Download data file
  command: /usr/bin/wget https://datasets.imdbws.com/name.basics.tsv.gz
  when: hasData == False

- name: Extract the data file
  command: /usr/bin/gzip -d /home/ec2-user/name.basics.tsv.gz
  when: hasData == False

- name: Rename the data file
  command: /usr/bin/mv /home/ec2-user/name.basics.tsv /home/ec2-user/data.tsv
  when: hasData == False

- name: Copying Producer binary file
  copy:
    src: producer.go
    dest: /home/ec2-user/producer.go

- name: Installing necessary go libraries
  command: /usr/bin/go get -u -v gopkg.in/confluentinc/confluent-kafka-go.v1/kafka

- name: Building Go script binary
  command:
    cmd: /usr/bin/go build producer.go
    chdir: /home/ec2-user/

- name: Copying Producer Service file
  copy:
    src: producer.service
    dest: /etc/systemd/system/producer.service
  notify:
    - Reload Daemons
    - Restart Producer service

- name: Downloading Kafka Binaries
  get_url:
    url: https://mirror.olnevhost.net/pub/apache/kafka/2.7.0/kafka_2.13-2.7.0.tgz
    dest: /home/ec2-user

- name: Extract the Kafka Binaries
  command:
    cmd: /usr/bin/tar -xvzf kafka_2.13-2.7.0.tgz
    chdir: /home/ec2-user

- name: Create the neccessary directory
  command:
    cmd: /usr/bin/mkdir data/kafka data/zookeeper
    chdir: /home/ec2-user/kafka_2.13-2.7.0/

- name: Modifying the zookeeper.properties
  lineinfile:
    path: /home/ec2-user/kafka_2.13-2.7.0/config/zookeeper.properties
    regexp: '^dataDir='
    line: dataDir=/home/ec2-user/kafka_2.13-2.7.0/data/zookeeper/

- name: Modifying the server.properties
  lineinfile:
    path: /home/ec2-user/kafka_2.13-2.7.0/config/server.properties
    regexp: '^log.dirs='
    line: log.dirs=/home/ec2-user/kafka_2.13-2.7.0/data/kafka

- name: Copying Kafka service file
  copy:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service
  notify:
    - Reload Daemons
    - Restart Kafka service

- name: Copying Zookeeper service file
  copy:
    src: zookeeper.service
    dest: /etc/systemd/system/zookeeper.service
  notify:
    - Reload Daemons
    - Restart Zookeeper service

- name: Start and Enable Producer Service
  service:
    name: producer
    enabled: yes
    state: started

- name: Start and Enable Kafka Service
  service:
    name: kafka
    enabled: yes
    state: started

- name: Start and Enable Zookeeper Service
  service:
    name: zookeeper
    enabled: yes
    state: started