---
# tasks file for bastion
- name: Update the instance
  yum:
    name: "*"
    state: latest
    update_only: yes

- name: Install git, wget, go, 
  yum:
    name:
      - git
      - wget
      - go