---
# tasks file for bastion
- name: Update the instance
  yum:
    name: "*"
    state: latest
    update_only: yes
  become: yes
  become_user: root
- name: Install git, wget,
  yum:
    name:
      - git
      - wget
    state: latest
  become: yes
  become_user: root