apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /tmp/nginx
          readOnly: true
        - name: nginx-ssh-secret
          mountPath: /root/.ssh/id_rsa
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: nginx-ssh-secret
        secret:
          secretName: nginx-ssh-secret
          defaultMode: 0600
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: my-nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31384
  type: NodePort