- hosts: kafka
  roles:
    - role: './roles/kafka/'
  environment:
    GOPATH: "/home/ec2-user/go"
    # GOROOT: "/root/go"
- hosts: webserver1
  roles:
    - role: './roles/webserver/'
  vars:
    webserver_num: 1
- hosts: webserver2
  roles:
    - role: './roles/webserver/'
  vars:
    webserver_num: 2
- hosts: webserver3
  roles:
    - role: './roles/webserver/'
  vars:
    webserver_num: 3
- hosts: bastion
  roles:
    - role: './roles/bastion/'